# Generated by Django 3.0.7 on 2020-08-22 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Posted on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Edit'),
        ),
    ]
