# Generated by Django 3.0.7 on 2020-08-16 13:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAsstReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField(blank=True, default=None, null=True, verbose_name='Additional Info')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='On')),
                ('asst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.DocAsstProfile', verbose_name='Assistant')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.DoctorProfile', verbose_name='Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=32, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('discount_percent', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Total Discount Percent (1-100)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.DoctorProfile', verbose_name='Created by')),
            ],
        ),
    ]
