# Generated by Django 3.0.7 on 2020-09-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200923_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False, null=True, verbose_name='Seen'),
        ),
    ]
