# Generated by Django 3.0.7 on 2020-08-16 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='Username')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Join Date')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last Login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(default='', max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(default='', max_length=30, verbose_name='Last Name')),
                ('dob', models.DateField(null=True, verbose_name='Date of Birth')),
                ('address', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Town/City')),
                ('district', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='District')),
                ('gender', models.CharField(choices=[('-', 'Unavailable'), ('M', 'Male'), ('F', 'Female')], default='-', max_length=1)),
                ('blood_group', models.CharField(choices=[('-', 'Unavailable'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='-', max_length=3)),
                ('user_type', models.CharField(choices=[('P', 'Patient'), ('D', 'Doctor'), ('DA', "Doctor's Assistant")], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='patient_profile_pics')),
                ('height_cm', models.IntegerField(blank=True, default=None, null=True, verbose_name='Height (cm)')),
                ('weight_kg', models.IntegerField(blank=True, default=None, null=True, verbose_name='Weight (kg)')),
                ('bloodPressure', models.BooleanField(blank=True, default=None, null=True, verbose_name='Blood Pressure')),
                ('diabetes', models.BooleanField(blank=True, default=None, null=True, verbose_name='Diabetes')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='doctor_profile_pics')),
                ('review_rating', models.FloatField(default=0.0, verbose_name='Rating')),
                ('total_review', models.IntegerField(default=0, verbose_name='Number of Reviews')),
                ('bio_desc', models.TextField(default='No information available', verbose_name='Doctor Bio')),
                ('specialist', models.BooleanField(null=True, verbose_name='Specialist')),
                ('education', models.CharField(default='N/A', max_length=250, verbose_name='Education')),
                ('exp_years', models.IntegerField(default=0, verbose_name='Experience (years)')),
                ('total_num_of_chember', models.IntegerField(default=0, verbose_name='Total number of Chembers')),
                ('field', models.CharField(default='N/A', max_length=100, verbose_name='Field of Expertise')),
                ('approx_fee_range_high', models.IntegerField(default=0, verbose_name='Approx. Fee Range (Highest)')),
                ('approx_fee_range_low', models.IntegerField(default=0, verbose_name='Approx. Fee Range (Lowest)')),
                ('apprived', models.BooleanField(default=False, verbose_name='Approved')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('seach_tags', models.TextField(blank=True, default=None, null=True, verbose_name='Search Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocAsstProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='docasst_profile_pics')),
                ('doctor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.DoctorProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
