# Generated by Django 3.0.7 on 2020-08-16 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Hospital Name')),
                ('phone_number', models.CharField(max_length=14, verbose_name='Phone Number')),
                ('image', models.ImageField(default='no_image.jpg', upload_to='hospitals')),
                ('address', models.CharField(max_length=60, verbose_name='Address')),
                ('city', models.CharField(max_length=60, verbose_name='City')),
                ('district', models.CharField(max_length=60, verbose_name='District')),
                ('additional_info', models.TextField(blank=True, default='', verbose_name='Additional Info')),
                ('name_in_google_maps', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name in Google Map')),
                ('doctors', models.ManyToManyField(to='user.DoctorProfile', verbose_name='Doctor(s) available in this hospital')),
                ('managers', models.ManyToManyField(related_name='manages', to='user.DoctorProfile', verbose_name='Manager Doctor(s)')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('fee', models.IntegerField(blank=True, default=0, null=True, verbose_name='Fee')),
                ('total_available_slot', models.IntegerField(blank=True, null=True, verbose_name='Total Available Slots')),
                ('booked_slot', models.IntegerField(blank=True, default=0, null=True, verbose_name='Total Booked Slots')),
                ('chember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.Hospital')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.DoctorProfile', verbose_name='Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=60, verbose_name='Issue Title')),
                ('issue_desc', models.TextField(blank=True, default='', verbose_name='Issue Description')),
                ('status', models.CharField(default='Awaiting Confirmation', max_length=48, verbose_name='Status')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.PatientProfile', verbose_name='Patient')),
                ('ref_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Referenced By')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medic.DoctorsSchedule', verbose_name='Schedule')),
            ],
        ),
    ]
