# Generated by Django 3.0.7 on 2020-08-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorsschedule',
            name='rescheduled',
            field=models.BooleanField(default=False, verbose_name='Rescheduled (Y/N)'),
        ),
        migrations.AddField(
            model_name='doctorsschedule',
            name='rescheduled_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Rescheduled on'),
        ),
    ]
