# Generated by Django 3.0.7 on 2020-08-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0003_auto_20200827_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Awaiting Confirmation'), (1, 'Waiting for Payment'), (2, 'Confirmed'), (3, 'Cancelled')], default=0),
        ),
    ]
