# Generated by Django 3.0.7 on 2020-09-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medic', '0004_auto_20200830_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active (Y/N)'),
        ),
    ]
